#pragma once
#define PLAYERS_PER_TEAM 5
#define CHANCE_TO_JOIN_EXISTING_MATCH 50
#define CHANCE_TO_PLANT_BOMB 50
#define CHANCE_TO_DEFUSE_BOMB 50
#define CHANCE_TO_FIND_PLANTER 50
#define CHANCE_TO_FIND_DEFUSER 50
#define CHANCE_TO_SHOOT_FIRST 50
#define RANDOM_DAMAGE_ADJUST 10
#define DEFUSE_TIME 3